name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # This is where you place your autograding tests
      # For more information on this runner, see the documentation at: https://github.com/classroom-resources/autograding-io-grader
      #
      # For example, you could run a test suite like this:
    - name: Check for Aufgabe.md
      id: aufgabe-md
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: "Aufgabe-md"
        command: "find . -name Aufgabe.md"
        expected-output: ./Aufgabe.md
        comparison-method: exact
        max-score: 1
    - name: Check for Screenshot
      id: screenshot
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: "Screenshot"
        command: "find . -name Init.png -o -name Init.jpg"
        expected-output: ./Init.(png|jpg)
        comparison-mode: regex
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      # For more information on this runner, see the documentation at https://github.com/classroom-resources/autograding-grading-reporter
      # To output the results of the tests, you can use the
      # autograding-grading-reporter action like this:
      env:
        TEST_RESULTS: "${{ steps.test.outputs.result }}"
      with:
        runners: test